### ISSUE TITLE
Training on new data in scierc format

### ISSUE THREAD

**Issue by Kehindeajayi01** [dwadden/dygiepp#92] opened 2022-02-10 18:12 UTC
Hi dwadden,
Thanks for the great work. I am trying to train your model on a new data that's in scierc format. I have used the brat_input.py to convert my .ann and .txt to scierc format. However when I ran the training script on my data, I got the error below:

<img width="566" alt="Screen Shot 1400-11-21 at 13 08 15" src="https://user-images.githubusercontent.com/43017928/153470185-bd20f132-b823-4b81-9679-7d74e8805d9f.png">

**Comment by dwadden** [comment] 2022-02-12 04:13
Hi,

Can you please attach a minimal example (ideally a single line from a `jsonl` file) that reproduces this error, along with the model training command you use to start training?

Dave

**Comment by Kehindeajayi01** [comment] 2022-02-13 23:08
> Hi,
> 
> Can you please attach a minimal example (ideally a single line from a `jsonl` file) that reproduces this error, along with the model training command you use to start training?
> 
> Dave


<img width="677" alt="Screen Shot 2022-02-13 at 3 06 54 PM" src="https://user-images.githubusercontent.com/43017928/153779352-ac433381-ad04-4d08-9e82-0d0cb25c6c26.png">


This is the training command I used: bash scripts/train.sh scierc_lightweight

**Comment by dwadden** [comment] 2022-03-07 23:13
Sorry for the slow response.
Could you include the example as a file attachment rather than as a screenshot?

**Comment by Kehindeajayi01** [comment] 2022-03-10 20:04
> Sorry for the slow response. Could you include the example as a file attachment rather than as a screenshot?
Please find the attached for the requested file.

[dygie_example.txt](https://github.com/dwadden/dygiepp/files/8226872/dygie_example.txt)

Thanks

**Comment by dwadden** [comment] 2022-03-15 22:16
In your example, one of your `relations` has value `[109, 109, null, null, "has_unit"]`. The code is breaking due to the presence of `null` values.

**Comment by dwadden** [comment] 2022-03-17 22:21
I'll close this. Feel free to re-open if this doesn't solve your problem.

**Comment by Kehindeajayi01** [comment] 2022-03-17 22:23
> In your example, one of your `relations` has value `[109, 109, null, null, "has_unit"]`. The code is breaking due to the presence of `null` values. See [data.md](https://github.com/dwadden/dygiepp/blob/master/doc/data.md) on the required format for input data.

The null were introduced by your brat_input.py script when I used it to convert the brat format to your format

**Comment by dwadden** [comment] 2022-03-17 22:44
Ah I see, sorry for closing prematurely.

`brat_to_input.py` was added by a contributor; more info [here](https://github.com/dwadden/dygiepp/issues/92). I unfortunately can't offer support, but maybe @serenalotreck can help?

**Closed** 2022-07-02 21:19 UTC
