### ISSUE TITLE
Training on WLP dataset?

### ISSUE THREAD

**Issue by ronentk** [dwadden/dygiepp#14] opened 2020-03-12 14:35 UTC
Hi,
Are you planning to release the code for training a model on the WLP corpus as well?

Thanks!

**Comment by dwadden** [comment] 2020-05-26 00:11
Still working on this. An undergrad did the data preprocessing and has since moved on, so I need to track down and re-run her code. Sorry for the delay.

**Comment by dwadden** [comment] 2020-09-19 21:32
Hi @ronentk, sorry I've been so slow on this. I managed to track down what I think was the preprocessing script that we used, but I actually don't have the WLPC data anymore and it's not publicly available. I don't have the bandwidth to re-process the data and re-train a model, so I think I'm going to have to punt on this.

If you have the dataset, I'm happy to share the script I have with you. If you're trying to reproduce the results of our work, I'll help make sure that's possible.

Closing this issue.

**Closed by dwadden** 2020-09-19 21:32 UTC
