### ISSUE TITLE
DygieppPipe not working

### ISSUE THREAD

**Issue by tomhoper** [dwadden/dygiepp#89] opened 2022-01-26 14:26 UTC
I've tried loading several pre-trained models with  `DygieppPipe` (imported from `dygie.spacy_interface.spacy_interface`) -- `scierc`, `mechanic` (coarse/granular), `genia` -- get errors raised in `make_output_human_readable.py`. Each model raises different errors so I'm not going to clutter it here, but they all seem to be around `output_dict` not having some keys. Happy to share more details if needed.

@e3oroush @dwadden

**Comment by dwadden** [comment] 2022-01-27 04:51
I took a quick look to confirm that this wasn't caused by my recent commits over the last week or so, which were made to fix a . As far as I can tell, this problem is unrelated to the changes I made. I've found two issues:

1. Things seem to break for any model that performs coreference resolution. That's what going on with the `top_spans` error that @tomhoper identified. I think this is likely because some necessary model input isn't being passed in correctly, but I haven't debugged further.
2. The input `dataset` is being set to `scierc` when inputs are passed into the model [here](https://github.com/dwadden/dygiepp/blob/master/dygie/spacy_interface/spacy_interface.py#L111). This will break for any model that was trained on a dataset other than `scierc`; see [here](https://github.com/dwadden/dygiepp/blob/master/README.md#working-with-new-datasets) for more information.

The Jupyter demo works at present because it uses the `scierc-lightweight` model, which (1) doesn't perform coreference resolution, and (2) was trained on `scierc`.

 I unfortunately don't have bandwidth to add these features. @e3oroush, if you are able to fix this, feel free to submit a PR. I'm happy to provide help if you get stuck. If not, could you please update the docs and Jupyter notebook indicating which models the spacy interface will work for?

Thanks all!

**Comment by e3oroush** [comment] 2022-01-29 14:01
I tried to look into your source codes to find out what the problem was, but unfortunately I couldn't figure it out.  
Can you help me with that? I just tried to imitate the codes written in Predictors file in [here](https://github.com/dwadden/dygiepp/blob/e52887b24975ceeccf5aa680ce8ce55d8ead14e8/dygie/predictors/dygie.py#L56), but apparently not.  
Which part of the project is using this file? I'm pretty sure `allennlp evaluate` command doesn't.  
I'd like to fix the bug, because it seems to be a really tiny one.

**Comment by dwadden** [comment] 2022-01-30 20:39
The prediction code is used by the `allennlp predict` command. There's an example in the [README](https://github.com/dwadden/dygiepp#making-predictions-on-existing-datasets).
One way I can think of debugging would be to print out what a single [instance](https://github.com/dwadden/dygiepp/blob/master/dygie/predictors/dygie.py#L53) looks like when you make predictions using `allennlp predict`, compared to what it looks like using the Spacy pipeline. There must be a discrepancy in the way the input is being passed to the model. You may need to dig into the AllenNLP [predictor.py](https://github.com/allenai/allennlp/blob/dcc9cdc763a92bdd078128b760399a85449faea5/allennlp/predictors/predictor.py) file in order to figure out what's happening, since the dygie `Predictor` subclasses AllenNLP's `Predictor`. Make sure you're looking at version 1.1 of AllenNLP. 

There's still the issue that the model will break if you specify the input dataset as [scierc](https://github.com/dwadden/dygiepp/blob/master/dygie/spacy_interface/spacy_interface.py#L111), but the model was trained on a different dataset. I think the easiest fix here is:
- Look at the available label namespaces for the model. Here are the label spaces for [ner](https://github.com/dwadden/dygiepp/blob/master/dygie/models/ner.py#L43), [relations](https://github.com/dwadden/dygiepp/blob/master/dygie/models/relation.py#L39), and [events](https://github.com/dwadden/dygiepp/blob/master/dygie/models/events.py#L42). 
- Set the `dataset` field when you [pass in the data](https://github.com/dwadden/dygiepp/blob/master/dygie/spacy_interface/spacy_interface.py#L111) to match the model's label namespace.

More info on why this label namespace stuff is necessary can be found in [model.md](https://github.com/dwadden/dygiepp/blob/master/doc/model.md#multi-dataset-training). Sorry for the (perhaps needless) complexity. If I had time to re-write this repo from scratch I'd do things differently.

**Comment by e3oroush** [comment] 2022-01-31 22:38
Thanks a ton. I wasn't comfortable using allennlp API, but thanks to this project I'm catching up.  
I will try to fix this bug over the weekend and make sure everyone can can use all the available models.

**Comment by dwadden** [comment] 2022-02-01 17:52
Great, thanks! Let me know if you've got more questions.

**Comment by e3oroush** [comment] 2022-03-06 09:55
Sorry that took me so long, I didn't forget, just was occupied with lots of other stuffs (from getting Covid to passing exams lol).  
But the source was a silly mistake from my side. Now it should be resolved.

**Comment by dwadden** [comment] 2022-03-15 21:57
I just merged the PR. This fixes problem (1) mentioned above, but not the issue raised by @tomhoper is still present.

**Comment by e3oroush** [comment] 2022-03-15 23:52
Sorry that I didn't get the second problem. I just added another [PR](https://github.com/dwadden/dygiepp/pull/96) to fix that issue.

**Comment by dwadden** [comment] 2022-03-17 22:38
Nice, thanks!

@tomhoper you can now predict using Mechanic in [spacy-interface-example.ipynb](https://github.com/dwadden/dygiepp/blob/master/notebooks/spacy-interface-example.ipynb) like so:

```
component = DygieppPipe(nlp,pretrained_filepath="../pretrained/mechanic-coarse.tar.gz", dataset_name="None")
nlp.add_pipe(component)
doc = nlp(text)
```

Closing, since I think this is fixed. Please re-open if not.

**Comment by dwadden** [comment] 2022-03-17 22:38
Nice, thanks!

@tomhoper you can now predict using Mechanic in [spacy-interface-example.ipynb](https://github.com/dwadden/dygiepp/blob/master/notebooks/spacy-interface-example.ipynb) like so:

```
component = DygieppPipe(nlp,pretrained_filepath="../pretrained/mechanic-coarse.tar.gz", dataset_name="None")
nlp.add_pipe(component)
doc = nlp(text)
```

Closing, since I think this is fixed. Please re-open if not.

**Comment by tomhoper** [comment] 2022-03-19 18:10
Thank you @e3oroush and @dwadden.
`mechanic-coarse` is now working, but `mechanic-granular` (an "event" model) is not. Here's the error i'm getting:

`line 331, in make_output_human_readable
    for predictions, sentence in zip(output_dict["events"]["predictions"], doc):
KeyError: 'predictions'
`

Any ideas?

**Comment by tomhoper** [comment] 2022-03-20 09:53
@dwadden i made a pull request that adds spacy support for "events" (namely `mechanic-granular` but should work in general).  #99  
also added a notebook with examples using and comparing `mechanic-coarse `and  `mechanic-granular` on some scientific documents.

**Comment by dwadden** [comment] 2022-03-21 17:44
Just responded to the PR.

**Closed** 2022-07-02 21:19 UTC
